spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.102.98.244:3306/job?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zxq.cloud.model

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

